### ISSUE TITLE
How do we access this library on Nuget 

### ISSUE THREAD

**Issue by artizani** [aws-samples/aws-services-netcore-wrappers#2]
There is a confusing (old ) nuget package called DynamoDB.Repository. I confused that package for this. Maybe package a library/dll and tag it for us to use.

When you do build the package locally, the correct import statement is 

using Amazon.DynamoDb.Wrapper.Extensions;

https://www.nuget.org/packages/DynamoDB.Repository.

**Comment by artizani** [comment]
_dynamoDBRepository.GetTableName seems to be depracated, How do we get table name

**Comment by Nisha2015** [comment]
Hi @artizani , 

Currently there is no nuget package published for this. I will look into the deprecated library being used by the code and update the status here. Thanks for reporting.

Nisha

**Comment by ankushjain358** [comment]
Hi @artizani 

`_dynamoDBRepository.GetTableName` method is not deprecated, it has been kept private since it is being used at only one place within the library. If you want to use this method, then you can make it public from `DynamoDBGenericRepository` class. This method makes use of reflection to read the `DynamoDBTableAttribute` value from the entity class when using .NET Object Persistence Model. 

Also, please let us know if there is a use case, we can expose it via interface.

Ankush

**Comment by ankushjain358** [comment]
> _dynamoDBRepository.GetTableName seems to be depracated, How do we get table name

Hi @artizani 

`_dynamoDBRepository.GetTableName` method is not deprecated, it has been kept private since it is being used at only one place within the library. If you want to use this method, then you can make it public from `DynamoDBGenericRepository` class. This method makes use of reflection to read the `DynamoDBTableAttribute` value from the entity class when using .NET Object Persistence Model. 

Also, please let us know if there is a use case, we can expose it via interface.

Ankush

**Comment by Nisha2015** [comment]
@artizani , for the namespace issue you reported in README file, it's been fixed and merged. Please let us know if you have any further questions or if we are good to close this issue.

**Comment by artizani** [comment]
@ankushjain358 Can we have a sample project instead of snippets you have readme.  some snippets are out of date, we can keep the a reference to the sample files from snippets in read me. Thanks

**Comment by Nisha2015** [comment]
@artizani , sure we will add a sample dynamodb consumer client and will also change README accordingly.

**Comment by Nisha2015** [comment]
@artizani , we have included a sample dynamodb client at https://github.com/aws-samples/aws-services-netcore-wrappers/tree/main/samples/dynamodb-sample-app. 
Please have a look and let us know if you have any further questions.
